[build]
  command = "npm run build"
  publish = "public"

[dev]
  command = "npm run dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/404.html"
  to = "/404/"
  status = 404

[forms]
  email = "davidelopresti0129@gmail.com"
